account_id = "574fdb1eae7e80782a805c4b92f6b626"
name = "remix-node-cloudflare"

compatibility_date = "2022-09-14"
compatibility_flags = ["streams_enable_constructors"]

main = "worker/index.ts"

[define]
"process.env.REMIX_DEV_SERVER_WS_PORT" = "8002"

[site]
bucket = "./public"
