name = "remix-node-cloudflare"

compatibility_date = "2022-09-14"
compatibility_flags = ["streams_enable_constructors"]

main = "worker/index.ts"

[site]
bucket = "./public"

[define]
"process.env.REMIX_DEV_SERVER_WS_PORT" = "8002"

[vars]
ORIGIN_URL = "http://localhost:3000"
